import type { Translations } from '@/lib/i18n';

export type AiCheckStrings = NonNullable<Translations['aiCheck']>;

export const defaultAiCheck: AiCheckStrings = {
  badge: 'AI Visibility',
  title: 'Does AI',
  titleHighlight: 'know your brand?',
  subtitle: 'Ask GPT directly whether it recognizes your website, knows your URL, and has accurate information about your business.',
  submit: 'Ask AI',
  scanning: 'Asking AI...',
  resultTitle: 'AI Visibility Result',
  knows: 'AI Recognition',
  doesNotKnow: 'AI Unknown',
  accuracy: 'Accuracy',
  accuracyLevels: {
    accurate: 'Accurate',
    partial: 'Partial',
    inaccurate: 'Inaccurate',
    unknown: 'Unknown',
  },
  urlKnown: 'URL Known',
  urlNotKnown: 'URL Not Known',
  knowledgeDepth: 'Knowledge Depth',
  depthLevels: {
    deep: 'Deep',
    moderate: 'Moderate',
    shallow: 'Shallow',
    none: 'None',
  },
  productsKnown: 'Products Known',
  productsNotKnown: 'Products Unknown',
  googlePresence: 'Google Presence',
  googleTop3: 'Top 3',
  googleTop5: 'Top 5',
  googleTop10: 'Top 10',
  googleLow: 'Low',
  googleNone: 'Not Found',
  aiOverview: 'AI Overview',
  aiOverviewFull: 'Full Entity',
  aiOverviewPartial: 'Knowledge Panel',
  aiOverviewAnswerOnly: 'Answer Only',
  aiOverviewNone: 'Not Indexed',
  scoreBreakdown: 'Score Breakdown',
  scoringCriteria: 'Scoring Criteria',
  labelWhyMatters: 'Why it matters',
  labelHowImprove: 'How to improve',
  labelHowDetect: 'How we detect this',
  criteriaItems: [
    { label: 'AI Recognition', max: '20', desc: 'Does the AI recognize this website?', why: '', howToImprove: '', howDetected: '' },
    { label: 'Accuracy', max: '15', desc: 'Is the AI\'s knowledge correct?', why: '', howToImprove: '', howDetected: '' },
    { label: 'URL Known', max: '10', desc: 'Can the AI provide the correct URL?', why: '', howToImprove: '', howDetected: '' },
    { label: 'Knowledge Depth', max: '15', desc: 'How deep is the AI\'s knowledge?', why: '', howToImprove: '', howDetected: '' },
    { label: 'Products/Services', max: '15', desc: 'Can AI name specific products?', why: '', howToImprove: '', howDetected: '' },
    { label: 'Google Presence', max: '10', desc: 'SEO ranking in Google search', why: '', howToImprove: '', howDetected: '' },
    { label: 'AI Overview', max: '15', desc: 'Is the brand in Google AI Overview?', why: '', howToImprove: '', howDetected: '' },
  ] as ReadonlyArray<{ readonly label: string; readonly max: string; readonly desc: string; readonly why: string; readonly howToImprove: string; readonly howDetected: string }>,
  summary: 'Summary',
  details: 'Details',
  model: 'Model',
  analyzeAnother: 'Check Another Website',
  skipped: 'Check was skipped',
  trustLabel1: 'GPT-4.1 nano',
  trustLabel2: 'Real AI Check',
  trustLabel3: 'Instant Result',
};
